In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import json
import ast

In [4]:
import geopandas as gpd
from shapely.geometry import Point
import kaleido

In [5]:
data=pd.read_csv('my_selected_areas.csv')
data

,parent,distance,keytag,importance,biz_ext,type,photos,building,typecode,shopinfo,...,pname,biz_type,cityname,childtype,atag,name,location,shopid,favorite_num,featured_reviews
0,[],[],咖啡,[],"{'cost': '25.00', 'opentime2': '周一至周日 10:00-20...",餐饮服务;咖啡厅;咖啡厅,"[{'title': [], 'url': 'https://store.is.autona...",[],050500,0,...,广东省,diner,广州市,[],"手冲,美式,卡布奇诺,Dirty,贝果/可颂+拿铁,拿铁,coffee",村里咖啡 cunlee coffee,"113.353610,23.173850",[],[],[]
1,[],[],咖啡,[],"{'cost': '13.00', 'opentime2': '周一至周日 09:00-21...",餐饮服务;咖啡厅;咖啡厅,"[{'title': [], 'url': 'https://store.is.autona...",[],050500,0,...,广东省,diner,广州市,[],"美式,拿铁,杨枝甘露瑞纳冰,海盐芝士厚乳拿铁,厚乳拿铁,生椰拿铁yyds,杨枝甘露,生椰拿铁",瑞幸咖啡(睿志创意园店),"113.349777,23.177381",[],[],[]
2,B0IUTM051A,[],咖啡,[],"{'cost': '22.00', 'opentime2': '周一至周五 07:00-18...",餐饮服务;咖啡厅;咖啡厅,"[{'title': [], 'url': 'https://store.is.autona...",[],050500,0,...,广东省,diner,广州市,202,生椰拿铁,瑞幸咖啡(优托邦长兴店),"113.347675,23.170625",[],[],[]
3,B0JRLM4DOG,[],咖啡,[],"{'cost': '32.00', 'opentime2': '周一至周日 06:45-22...",餐饮服务;咖啡厅;星巴克咖啡,"[{'title': [], 'url': 'http://store.is.autonav...",[],050501,1,...,广东省,diner,广州市,202,"卡布奇诺,星冰乐,下午茶,三明治",星巴克(广州长兴路店),"113.347858,23.169527",[],[],[]
4,[],[],咖啡,[],"{'cost': '14.00', 'opentime2': [], 'rating': '...",餐饮服务;咖啡厅;咖啡厅,"[{'title': [], 'url': 'https://store.is.autona...",[],050500,0,...,广东省,diner,广州市,[],"奶咖,生椰拿铁",NOWWA挪瓦咖啡(广州天河东大街店),"113.346007,23.174574",[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2123,[],[],商场,[],"{'cost': [], 'opentime2': '周一至周日 08:30-23:00',...",购物服务;商场;购物中心,"[{'title': [], 'url': 'https://aos-comment.ama...",[],060101,0,...,广东省,[],佛山市,[],[],嘉荟广场,"113.204889,23.093580",[],[],[]
2124,[],[],商场,[],"{'cost': [], 'opentime2': '周一至周日 09:00-18:30',...",购物服务;商场;购物中心,"[{'title': [], 'url': 'https://store.is.autona...",[],060101,0,...,广东省,[],广州市,[],[],沃野广场,"113.217797,23.049681",[],[],[]
2125,[],[],商场,[],"{'cost': [], 'opentime2': '周一至周日 09:00-21:00',...",购物服务;商场;购物中心,"[{'title': [], 'url': 'http://store.is.autonav...",[],060101,0,...,广东省,[],佛山市,[],[],海天广场,"113.208740,23.029127",[],[],[]
2126,[],[],商场,[],"{'cost': [], 'opentime2': '周一至周日 10:00-22:00',...",购物服务;商场;购物中心,"[{'title': [], 'url': 'http://store.is.autonav...",[],060101,0,...,广东省,[],广州市,[],[],新西关广场,"113.207219,23.110353",[],[],[]
2127,[],[],住宅区,[],"{'cost': [], 'opentime2': '周一至周日 00:00-24:00',...",购物服务;商场;购物中心,"[{'title': [], 'url': 'http://store.is.autonav...",[],060101,1,...,广东省,[],佛山市,[],[],佛山澳门城(建设中),"113.215304,23.030054",[],[],[]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2128 entries, 0 to 2127
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parent                   2128 non-null   object
 1   distance                 2128 non-null   object
 2   keytag                   2128 non-null   object
 3   importance               2128 non-null   object
 4   biz_ext                  2128 non-null   object
 5   type                     2128 non-null   object
 6   photos                   2128 non-null   object
 7   building                 2128 non-null   object
 8   typecode                 2128 non-null   object
 9   shopinfo                 2128 non-null   int64
 10  poiweight                2128 non-null   object
 11  adname                   2128 non-null   object
 12  featured_reviews_remake  2128 non-null   object
 13  tel                      2128 non-null   object
 14  id                       2128 non-null   object
 15  address                  2128 non-null   object
 16  space_num                2128 non-null   object
 17  pname                    2128 non-null   object
 18  biz_type                 2128 non-null   object
 19  cityname                 2128 non-null   object
 20  childtype                2128 non-null   object
 21  atag                     2128 non-null   object
 22  name                     2128 non-null   object
 23  location                 2128 non-null   object
 24  shopid                   2128 non-null   object
 25  favorite_num             2128 non-null   object
 26  featured_reviews         2128 non-null   object
dtypes: int64(1), object(26)
memory usage: 449.0+ KB

**数据评估与清洗:**

In [7]:
def parsed_biz_ext(x):
    if pd.isna(x) or x=='' or x=='[]':
        return {}
    try:
        return json.loads(x)
    except json.JSONDecodeError:
        return ast.literal_eval(x)
biz_ext=data['biz_ext'].apply(parsed_biz_ext)

In [8]:
biz_ext

0       {'cost': '25.00', 'opentime2': '周一至周日 10:00-20...
1       {'cost': '13.00', 'opentime2': '周一至周日 09:00-21...
2       {'cost': '22.00', 'opentime2': '周一至周五 07:00-18...
3       {'cost': '32.00', 'opentime2': '周一至周日 06:45-22...
4       {'cost': '14.00', 'opentime2': [], 'rating': '...
                              ...
2123    {'cost': [], 'opentime2': '周一至周日 08:30-23:00',...
2124    {'cost': [], 'opentime2': '周一至周日 09:00-18:30',...
2125    {'cost': [], 'opentime2': '周一至周日 09:00-21:00',...
2126    {'cost': [], 'opentime2': '周一至周日 10:00-22:00',...
2127    {'cost': [], 'opentime2': '周一至周日 00:00-24:00',...
Name: biz_ext, Length: 2128, dtype: object

In [9]:
rating=biz_ext.apply(lambda x: x.get('rating'))

In [10]:
rating.isnull().sum()

np.int64(0)

In [11]:
rating.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2128 entries, 0 to 2127
Series name: biz_ext
Non-Null Count  Dtype
--------------  -----
2128 non-null   object
dtypes: object(1)
memory usage: 16.8+ KB

In [12]:
cost=biz_ext.apply(lambda x: x.get('cost'))

In [13]:
cost.isnull().sum()

np.int64(0)

In [14]:
rating.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2128 entries, 0 to 2127
Series name: biz_ext
Non-Null Count  Dtype
--------------  -----
2128 non-null   object
dtypes: object(1)
memory usage: 16.8+ KB

In [15]:
new_data=data[['id', 'name', 'typecode', 'type', 'location', 'adname', 'address']]
new_data['rating']=rating
new_data['cost']=cost

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\4026070232.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['rating']=rating
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\4026070232.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['cost']=cost

In [16]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2128 entries, 0 to 2127
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        2128 non-null   object
 1   name      2128 non-null   object
 2   typecode  2128 non-null   object
 3   type      2128 non-null   object
 4   location  2128 non-null   object
 5   adname    2128 non-null   object
 6   address   2128 non-null   object
 7   rating    2128 non-null   object
 8   cost      2128 non-null   object
dtypes: object(9)
memory usage: 149.8+ KB

In [17]:
new_data[['longitude','latitude']]=new_data['location'].str.split(',',expand=True).astype(float)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\4130981823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data[['longitude','latitude']]=new_data['location'].str.split(',',expand=True).astype(float)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\4130981823.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data[['longitude','latitude']]=new_data['location'].str.split(',',expand=True).astype(float)

In [18]:
new_data['typecode_1']=0
for index,row in new_data.iterrows():
    new_data.loc[index,'typecode_1']=row['typecode'][0:6]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\1962956085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['typecode_1']=0
C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\1962956085.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '050500' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  new_data.loc[index,'typecode_1']=row['typecode'][0:6]

In [19]:
new_data['adname'].value_counts()

adname
天河区    716
越秀区    685
荔湾区    442
白云区    136
海珠区     92
南海区     55
黄埔区      2
Name: count, dtype: int64

In [20]:
delete=new_data.query('adname==["白云区","南海区","黄埔区"]').index

In [21]:
for a in new_data.index:
    if a in delete:
        new_data=new_data.drop(a)

In [22]:
new_data.sort_index()

,id,name,typecode,type,location,adname,address,rating,cost,longitude,latitude,typecode_1
0,B0LD7HY1S0,村里咖啡 cunlee coffee,050500,餐饮服务;咖啡厅;咖啡厅,"113.353610,23.173850",天河区,长湴东路26号一层,4.4,25.00,113.353610,23.173850,050500
1,B0I1RBW2GA,瑞幸咖啡(睿志创意园店),050500,餐饮服务;咖啡厅;咖啡厅,"113.349777,23.177381",天河区,白沙水路77号睿志创意园一层102号,4.3,13.00,113.349777,23.177381,050500
2,B0JD0ASWDF,瑞幸咖啡(优托邦长兴店),050500,餐饮服务;咖啡厅;咖啡厅,"113.347675,23.170625",天河区,长兴路13号长兴优托邦商场A1-126号底商,4.3,22.00,113.347675,23.170625,050500
3,B0H17454VL,星巴克(广州长兴路店),050501,餐饮服务;咖啡厅;星巴克咖啡,"113.347858,23.169527",天河区,长兴路13号首层085,4.5,32.00,113.347858,23.169527,050501
4,B0L0YA62R2,NOWWA挪瓦咖啡(广州天河东大街店),050500,餐饮服务;咖啡厅;咖啡厅,"113.346007,23.174574",天河区,元岗街下元岗东大街12号之2号,3.8,14.00,113.346007,23.174574,050500
...,...,...,...,...,...,...,...,...,...,...,...,...
2120,B0FFL2JD0J,谊园b馆写字楼,120201,商务住宅;楼宇;商务写字楼,"113.237825,23.111445",荔湾区,黄沙后道谊园(黄沙地铁站C口步行290米),[],[],113.237825,23.111445,120201
2121,B0J6L7UAHN,花地商业中心,060101,购物服务;商场;购物中心,"113.229441,23.095429",荔湾区,芳村百花路8-10号,4.2,[],113.229441,23.095429,060101
2122,B0FFHWIDJ0,花地商业中心西区,060101,购物服务;商场;购物中心,"113.229039,23.095161",荔湾区,百花路8-10号,3.9,[],113.229039,23.095161,060101
2124,B0FFG0G89O,沃野广场,060101,购物服务;商场;购物中心,"113.217797,23.049681",荔湾区,芳村沙尾立交桥与花地大道南交叉口北150米(鸿天中心旁),4.3,[],113.217797,23.049681,060101
2126,B0FFF3V42O,新西关广场,060101,购物服务;商场;购物中心,"113.207219,23.110353",荔湾区,芳兴路7号(滘口地铁站A2口步行370米),4.1,[],113.207219,23.110353,060101

In [23]:
new_data['typ_co_bro']=0
for index_1,row_1 in new_data.iterrows():
    new_data.loc[index_1,'typ_co_bro']=row_1['typecode_1'][0:3]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\317733223.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '050' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  new_data.loc[index_1,'typ_co_bro']=row_1['typecode_1'][0:3]

In [24]:
analyse_data=new_data.drop(['typecode','location'],axis=1)

In [25]:
analyse_data

,id,name,type,adname,address,rating,cost,longitude,latitude,typecode_1,typ_co_bro
0,B0LD7HY1S0,村里咖啡 cunlee coffee,餐饮服务;咖啡厅;咖啡厅,天河区,长湴东路26号一层,4.4,25.00,113.353610,23.173850,050500,050
1,B0I1RBW2GA,瑞幸咖啡(睿志创意园店),餐饮服务;咖啡厅;咖啡厅,天河区,白沙水路77号睿志创意园一层102号,4.3,13.00,113.349777,23.177381,050500,050
2,B0JD0ASWDF,瑞幸咖啡(优托邦长兴店),餐饮服务;咖啡厅;咖啡厅,天河区,长兴路13号长兴优托邦商场A1-126号底商,4.3,22.00,113.347675,23.170625,050500,050
3,B0H17454VL,星巴克(广州长兴路店),餐饮服务;咖啡厅;星巴克咖啡,天河区,长兴路13号首层085,4.5,32.00,113.347858,23.169527,050501,050
4,B0L0YA62R2,NOWWA挪瓦咖啡(广州天河东大街店),餐饮服务;咖啡厅;咖啡厅,天河区,元岗街下元岗东大街12号之2号,3.8,14.00,113.346007,23.174574,050500,050
...,...,...,...,...,...,...,...,...,...,...,...
2120,B0FFL2JD0J,谊园b馆写字楼,商务住宅;楼宇;商务写字楼,荔湾区,黄沙后道谊园(黄沙地铁站C口步行290米),[],[],113.237825,23.111445,120201,120
2121,B0J6L7UAHN,花地商业中心,购物服务;商场;购物中心,荔湾区,芳村百花路8-10号,4.2,[],113.229441,23.095429,060101,060
2122,B0FFHWIDJ0,花地商业中心西区,购物服务;商场;购物中心,荔湾区,百花路8-10号,3.9,[],113.229039,23.095161,060101,060
2124,B0FFG0G89O,沃野广场,购物服务;商场;购物中心,荔湾区,芳村沙尾立交桥与花地大道南交叉口北150米(鸿天中心旁),4.3,[],113.217797,23.049681,060101,060
2126,B0FFF3V42O,新西关广场,购物服务;商场;购物中心,荔湾区,芳兴路7号(滘口地铁站A2口步行370米),4.1,[],113.207219,23.110353,060101,060

In [26]:
analyse_data.to_csv('poi_analyse_data.csv',index=False)

In [27]:
analyse_data['typ_co_bro']=analyse_data['typ_co_bro'].str.slice(0,-1)

In [28]:
co_analyse_data=analyse_data.copy()

In [29]:
co_analyse_data['rating'] = pd.to_numeric(co_analyse_data['rating'], errors='coerce')
co_analyse_data['cost'] = pd.to_numeric(co_analyse_data['cost'], errors='coerce')

In [30]:
co_analyse_data=co_analyse_data[['rating','cost','longitude','latitude','typ_co_bro']].copy()

In [31]:
coffee_data=co_analyse_data.dropna(subset=['rating','cost'])

In [32]:
coffee_data=coffee_data[coffee_data['typ_co_bro']=="05"].copy()

**Geopandas空间格式转换**

In [33]:
points=[Point(xy) for xy in zip(co_analyse_data['longitude'],co_analyse_data['latitude'])]

In [34]:
poi_geo_data=gpd.GeoDataFrame(co_analyse_data,geometry=points,crs="EPSG:4326")

In [35]:
poi_geo_data['name']=analyse_data['name'].copy()

In [36]:
geometry_target=poi_geo_data[poi_geo_data['name'].str.contains('星巴克', na=False)].copy()

In [37]:
geometry_competitor=poi_geo_data[poi_geo_data['name'].str.contains('瑞幸咖啡|库迪咖啡', na=False)].copy()

In [38]:
print(f"目标品牌（星巴克）门店数量：{len(geometry_target)}")
print(f"竞品（瑞幸咖啡和库迪咖啡）门店数量：{len(geometry_competitor)}")

目标品牌（星巴克）门店数量：47
竞品（瑞幸咖啡和库迪咖啡）门店数量：117

In [39]:
geometry_target = geometry_target.to_crs("EPSG:32650")
geometry_competitor = geometry_competitor.to_crs("EPSG:32650")

In [40]:
geometry_target['buffer']=geometry_target['geometry'].buffer(distance=1000)
geometry_competitor['buffer']=geometry_competitor['geometry'].buffer(distance=1000)

In [41]:
geometry_target = geometry_target.reset_index(drop=False).rename(columns={'index': 'id'})

**计算目标品牌（星巴克）内部缓冲区重叠度：**

In [42]:
buffers = geometry_target[['id', 'buffer']].copy()
buffers = buffers.set_geometry('buffer')

In [43]:
#自身空间连接，找出所有相交对（包括自身）
intersect_pairs = gpd.sjoin(buffers, buffers, how='inner', predicate='intersects')

In [44]:
# 过滤掉自身
intersect_pairs_screen=intersect_pairs[intersect_pairs['id_left']!=intersect_pairs['id_right']].copy()

In [45]:
#计算每对交集的面积
def compute_intersection_area(row):
    buf_left = buffers.loc[buffers['id'] == row['id_left'], 'buffer'].values[0]
    buf_right = buffers.loc[buffers['id'] == row['id_right'], 'buffer'].values[0]
    return buf_left.intersection(buf_right).area

intersect_pairs_screen['area'] = intersect_pairs_screen.apply(compute_intersection_area, axis=1)

In [46]:
# 按id_left分组求和（每个门店与其他门店的缓冲区重叠总面积）
overlap_sum = intersect_pairs_screen.groupby('id_left')['area'].sum().reset_index()
overlap_sum.columns = ['id', 'overlap_area']

In [47]:
geometry_target = geometry_target.merge(overlap_sum, on='id', how='left').fillna(0)

In [48]:
# 计算缓冲区面积
geometry_target['buffer_area'] = geometry_target['buffer'].area

In [49]:
# 计算缓冲区重叠度
geometry_target['overlap_ratio'] = geometry_target['overlap_area'] / geometry_target['buffer_area']

**计算目标门店与竞品（瑞幸咖啡和库迪咖啡）的缓冲区重叠度：**

In [50]:
geometry_competitor = geometry_competitor.reset_index(drop=False).rename(columns={'index': 'id'})

In [51]:
buffers_competitor = geometry_competitor[['id', 'buffer']].copy()
buffers_competitor = buffers_competitor.set_geometry('buffer')

In [52]:
intersect_pairs_comp = gpd.sjoin(buffers, buffers_competitor, how='left', predicate='intersects')
intersect_pairs_comp_filtered = intersect_pairs_comp.dropna(subset=['index_right']).copy()

In [53]:
def compute_comp_intersection_area(row):
    buf_target = buffers.loc[buffers['id'] == row['id_left'], 'buffer'].values[0]
    buf_competitor = buffers_competitor.loc[buffers_competitor['id'] == row['id_right'], 'buffer'].values[0]
    return buf_target.intersection(buf_competitor).area

intersect_pairs_comp_filtered['comp_area'] = intersect_pairs_comp_filtered.apply(compute_comp_intersection_area, axis=1)

In [54]:
comp_overlap_sum = intersect_pairs_comp_filtered.groupby('id_left')['comp_area'].sum().reset_index()
comp_overlap_sum.columns = ['id', 'comp_overlap_area']

In [55]:
geometry_target = geometry_target.merge(comp_overlap_sum, on='id', how='left').fillna(0)

In [56]:
geometry_target['comp_overlap_ratio'] = geometry_target['comp_overlap_area'] / geometry_target['buffer_area']

In [57]:
print("\n目标品牌内部重叠度统计：")
print(geometry_target['overlap_ratio'].describe())
print("\n目标品牌与竞品重叠度统计：")
print(geometry_target['comp_overlap_ratio'].describe())

目标品牌内部重叠度统计：
count    47.000000
mean      3.660414
std       3.059800
min       0.000000
25%       1.202780
50%       2.863234
75%       5.913037
max       9.421633
Name: overlap_ratio, dtype: float64

目标品牌与竞品重叠度统计：
count    47.000000
mean      7.401207
std       3.787323
min       0.469689
25%       4.431607
50%       6.907165
75%      10.718899
max      13.440258
Name: comp_overlap_ratio, dtype: float64

**生成选址候选点：**

In [58]:
central_area=gpd.read_file(r'G:\数据分析作品集\广州市-中心区.GeoJSON')

Skipping field center: unsupported OGR type: 3
Skipping field centroid: unsupported OGR type: 3
Skipping field acroutes: unsupported OGR type: 1

In [59]:
central_area=central_area[central_area['name'].str.contains('天河区|越秀区|海珠区|荔湾区', na=False)].copy()

In [60]:
central_area=central_area[['name','geometry']].copy()

In [61]:
central_area_proj = central_area.to_crs("EPSG:32650")

In [62]:
min_x, min_y, max_x, max_y = central_area_proj.total_bounds
cellsize = 500  
x_coords = np.arange(min_x, max_x, cellsize)
y_coords = np.arange(min_y, max_y, cellsize)
candidate_points = [Point(x, y) for x in x_coords for y in y_coords]
candidates_gdf = gpd.GeoDataFrame(geometry=candidate_points,crs="EPSG:32650")

# 剔除落在不可建区域的点
candidates_gdf = candidates_gdf[candidates_gdf.within(central_area_proj.unary_union)]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\2748288743.py:9: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  candidates_gdf = candidates_gdf[candidates_gdf.within(central_area_proj.unary_union)]

In [63]:
print(f"\n生成候选选址点数量：{len(candidates_gdf)}")

生成候选选址点数量：1302

**候选点评分（核心指标计算）:**

In [64]:
#计算目标品牌覆盖程度
target_geom = geometry_target.geometry.unary_union  
candidates_gdf['dist_to_target'] = candidates_gdf.geometry.distance(target_geom)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\3930323437.py:2: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  target_geom = geometry_target.geometry.unary_union

In [65]:
comp_buffers_union = geometry_competitor['buffer'].unary_union
candidates_gdf['comp_overlap_area'] = candidates_gdf.geometry.intersection(comp_buffers_union).area

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9700\1757864453.py:1: DeprecationWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
  comp_buffers_union = geometry_competitor['buffer'].unary_union

In [66]:
#计算半径内竞品数量
comp_buffers_indiv = geometry_competitor['geometry'].buffer(1000)  
candidates_gdf['comp_count'] = candidates_gdf.geometry.apply(lambda x: comp_buffers_indiv.contains(x).sum())

In [67]:
import rasterio
from rasterstats import zonal_stats
from shapely.geometry import mapping

In [68]:
pop_raster = rasterio.open(r'G:\数据分析作品集\人口栅格数据\landscan-global-2024.tif')

In [69]:
candidates_utm = candidates_gdf.to_crs("EPSG:32650")

In [70]:
buffers_utm = candidates_utm.geometry.buffer(1000)

In [71]:
buffers_wgs84 = buffers_utm.to_crs("EPSG:4326")

In [72]:
buffers_gdf = gpd.GeoDataFrame(geometry=buffers_wgs84, crs="EPSG:4326")

In [73]:
#提取缓冲区范围内的人口总和
stats = zonal_stats(
    buffers_gdf,
    'G:/数据分析作品集/人口栅格数据/landscan-global-2024.tif',           
    stats=['sum'],              
    nodata=-2147483647,                
    geojson_out=False            
)

In [74]:
candidates_gdf['population_in_buffer'] = [s['sum'] for s in stats]

In [75]:
poi_geo_data_utm = poi_geo_data.to_crs("EPSG:32650")

In [76]:
shopping_malls=poi_geo_data_utm[poi_geo_data_utm['typ_co_bro']=='06'].copy()

In [77]:
malls_buffer=shopping_malls.geometry.buffer(1000)

In [78]:
#计算候选点指定半径内购物中心的数量
candidates_gdf['mall_count'] = candidates_gdf.geometry.apply(lambda p: malls_buffer.contains(p).sum())

In [79]:
offices=poi_geo_data_utm[poi_geo_data_utm['typ_co_bro']=='12'].copy()

In [80]:
offices_buffer=offices.geometry.buffer(1000)

In [81]:
#计算候选点指定半径内办公楼的数量
candidates_gdf['office_count']=candidates_gdf.geometry.apply(lambda p: offices_buffer.contains(p).sum())

In [82]:
subway=poi_geo_data_utm[poi_geo_data_utm['typ_co_bro']=='15'].copy()

In [83]:
subway_buffer=poi_geo_data_utm.geometry.buffer(1000)

In [84]:
#计算候选点指定半径内地铁出入口的数量
candidates_gdf['subway_count']=candidates_gdf.geometry.apply(lambda p: subway_buffer.contains(p).sum())

**归一化：**

In [85]:
from sklearn.preprocessing import MinMaxScaler

In [86]:
cols_to_normalized=['dist_to_target','comp_overlap_area','comp_count','population_in_buffer','mall_count','office_count','subway_count']

In [87]:
datas=candidates_gdf[cols_to_normalized]

In [88]:
normalized_data=MinMaxScaler().fit_transform(datas)

In [89]:
normalized_df=pd.DataFrame(normalized_data,columns=cols_to_normalized,index=candidates_gdf.index)

In [90]:
negative_cols=['dist_to_target','comp_overlap_area','comp_count']

In [91]:
for col in negative_cols:
    normalized_df[col]=1-normalized_df[col]

In [92]:
for cols in cols_to_normalized:
    candidates_gdf['norm_'+cols]=normalized_df[cols]

**加权综合得分：**

In [93]:
weights = {
    'norm_dist_to_target': 0.15,
    'norm_comp_overlap_area': 0.10,
    'norm_comp_count': 0.10,
    'norm_population_in_buffer': 0.30,
    'norm_mall_count': 0.15,
    'norm_office_count': 0.10,
    'norm_subway_count': 0.10
}

In [94]:
candidates_gdf['total_score'] = 0
for col,w in weights.items():
     candidates_gdf['total_score'] += candidates_gdf[col] * w

In [95]:
top_candidates=candidates_gdf.sort_values('total_score',ascending=False).head(10)

**文件保存：**

In [96]:
#geometry_target.to_parquet('geometry_target.parquet')
#geometry_competitor.to_parquet('geometry_competitor.parquet')
#poi_geo_data.to_parquet('poi_geo_data.parquet')

In [97]:
#candidates_gdf.to_file('candidates_gdf.geojson', driver='GeoJSON')

In [98]:
#co_analyse_data.to_csv('co_analyse_data.csv')

In [99]:
#coffee_data.to_csv('coffee_data.csv')

In [100]:
#analyse_data.to_csv('analyse_data.csv')

In [102]:
#malls_buffer.to_file('malls_buffer.shp')
#offices_buffer.to_file('offices_buffer.shp')
#subway_buffer.to_file('subway_buffer.shp')